plugins {
    id 'java-library'
}

group = 'com.tutem.platform'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-autoconfigure:3.5.4'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'
    implementation 'org.springframework.kafka:spring-kafka:3.3.7'
    implementation 'org.slf4j:slf4j-api:2.0.17'
    implementation 'org.junit.jupiter:junit-jupiter:5.10.2'

    //test
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
